# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

#Caching and parallel
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 1.7.5
mod_group = _1ms.McOverTor
mod_base_name = McOverTor

# Dependencies
fabric_api_version=0.145.2+26.1.1
